name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  fl_chart: ^0.68.0

  # --- Firebase ---
  firebase_core: 3.15.2
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  
  # --- Kamera & Utility ---
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  path_provider: ^2.1.3
  path: ^1.9.0
  screen_brightness: ^1.0.1 
  cupertino_icons: ^1.0.8


  # --- Tambahan WAJIB ---
  tflite_flutter: ^0.12.1
  image: ^4.1.7            
  cloud_functions: ^5.6.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Saya ganti ke versi yang lebih umum

flutter:
  uses-material-design: true

  # --- INI BAGIAN YANG DIPERBAIKI ---
  # Pastikan 'assets:' punya 2 spasi di depannya
  # Pastikan '- assets/...' punya 4 spasi di depannya
  assets:
    - assets/mobilefacenet.tflite